### ISSUE TITLE
Bug in GEOReverse config file

### ISSUE THREAD

**Issue by kumanji** [GEOUNED-code/GEOUNED#24]
In the GEOReverse config file, an error is given if cells has rangeType exclude while Materials has rangeType include.

```
[Cells]
rangeType = exclude
range = 90000:90119

[Materials]
rangeType = include
range = 1
```
produces the error
```
Traceback (most recent call last):
  File "geouned.py", line 50, in <module>
    reverse.reverse(inifile)
  File "C:\Users\kj7\GEOUNED-main\GEOUNED-main\src\GEOReverse\reverse.py", line 34, in reverse
    CADCells,fails = buildCAD(UnivCell,mcnp,CADselection)
  File "C:\Users\kj7\GEOUNED-main\GEOUNED-main\src\GEOReverse\Modules\buildCAD.py", line 26, in buildCAD
    levels,UniverseCells,modelSurfaces = data.GetFilteredCells(modelSurfaces,config) # filtered surfaces
  File "C:\Users\kj7\GEOUNED-main\GEOUNED-main\src\GEOReverse\Modules\MCNPinput.py", line 50, in GetFilteredCells
    FilteredCells[U] = selectCells(Universes[U],config)
  File "C:\Users\kj7\GEOUNED-main\GEOUNED-main\src\GEOReverse\Modules\MCNPinput.py", line 319, in selectCells
    if c.FILL is None:
AttributeError: 'int' object has no attribute 'FILL'
```

**Comment by psauvan** [comment]
fixed!
Thank you for your contribution
